//var fs = require('fs');
//Read and store prefixes and titles into an array
var prefixTitle = [ '',
'Lil',
'Spooky',
'Young',
'Yung',
'Smoke',
'$moke',
'Big',
'Sensei',
'Ugly',
'The ',
'Pretty',
'Player',
'Emo',
'D',
'B',
'Q',
'A',
'Rich',
'Goth',
'XXX',
'Tee ',
'Captain',
'Scary',
'Cap\'n',
'Snuff',
'Vroom',
'Dirty',
'Tight',
'Sport',
'Quiet',
'Smoke',
'Sky',
'Wicked',
'Blue',
'Robo',
'Chibi',
'Mortal',
'Yeah',
'Filthy',
'Gas',
'Funeral',
'Boogie',
'Global',
'Skate',
'Ski Mask',
'Death',
'Hate',
'Dat',
'Kill',
'Ghost',
'Spooky Ghost',
'Kid',
'Tha',
'This',
'Who is ',
'Who Killed',
'Whatever Happened To',
'Quiet',
'OG',
'Juice',
'Famous',
'Chief',
'Nice',
'Murda',
'Cool',
'Top',
'Da' ]
var firstName = [ 'Uzi',
  'Pump',
  'Worldstar',
  'Bars',
  'Xan',
  'Scooby',
  'Snax',
  'Blow',
  'Bump',
  'C',
  'Candy',
  'Toot',
  'Snow',
  'Bennie',
  'Truck',
  'Pep',
  'Dex',
  'Zing',
  'Smarties',
  'Purpp',
  'Smoke',
  'Boy',
  'Sizzurp',
  'Crank',
  'Moon',
  'Vert',
  'Glock',
  'Savage',
  'Thug',
  'Mortal',
  'Immortal',
  'Beatz',
  'Filthy',
  'Dragon',
  'Kill',
  'Whip',
  'Dip',
  'Post',
  'Cartoon',
  'Vitamin',
  'Oz',
  'Camp',
  'Dog',
  'Genie',
  'Boi',
  'Scarface',
  'Slump',
  'Gat',
  'Rocketlauncher',
  'Heat',
  'Tab',
  'Beatz',
  'AK',
  'AKA ',
  'Glock',
  'Sensei',
  'God',
  'Bangbang',
  'Xanny',
  'Montana',
  'Titan',
  'Glow',
  'Jammie',
  'Money',
  'Gat',
  'Smoke',
  'Glow',
  'Angry',
  'Sadboi',
  'Code',
  'Suicide',
  'Hungry',
  'Brappp',
  'Anime',
  'Goku',
  'Vegeta',
  'Master',
  'Raiden',
  'Zero',
  'Six ',
  'Coin',
  'Kenshi',
  'Eyes',
  'Chemical',
  'Five Hundred',
  'Haircut',
  'Dagger',
  'Kevin',
  'Merlin',
  'Wizard',
  'HK',
  'Sick',
  'Trippp',
  'Spooky Ghost',
  'Vicious',
  'Leanin',
  'Prometheus',
  'VC',
  'Double Cup',
  'Beastmaster',
  'Doublecup',
  'Rage',
  'Sober',
  'Drink',
  'Betrayal ',
  'Bart',
  'Facts',
  'Drop',
  '666',
  'OK',
  'Savage',
  'Nephew',
  'Delete',
  'Lex Luthor',
  'Villain',
  'Dutch',
  'Divine',
  '$talker',
  'Revenge',
  'Daddy',
  'Outlaw',
  'Death',
  'Poison',
  'Arsenic',
  'Alien',
  'OG',
  'Culture',
  'Boogie',
  'Never Broke',
  'The',
  'Tha',
  'Is',
  'Pew Pew',
  'Murda',
  'Kaneda',
  'No Life',
  'Saitama',
  'Name' ]
var lastSuffix = [ '',
  'God',
  'Vert',
  'Purpp',
  'Xan',
  'Beatz',
  'Get \'em',
  'K',
  'Q',
  'D',
  'Z',
  'Kill',
  'Whip',
  'Malone',
  'Boogie',
  'Boy',
  'Compton',
  'Hampton',
  'Stepson',
  'Jetson',
  'Dogs',
  'Pop',
  'Devil',
  'Wolverine',
  'Bonecrusher',
  'Tabs',
  'Beat',
  'Bang',
  'Smoke',
  'Sizzurp',
  'Green',
  'Black',
  'Red',
  'Dope',
  'Hazy',
  'Sleep',
  'Lasagna',
  'Chronic',
  'Trees',
  'Cube',
  'Blue',
  'Killer',
  'Killzzz',
  'Skunk',
  'Joker',
  'Fluff',
  'Vikes',
  'King',
  'Idiot',
  'Watson',
  'Xanny',
  'Xannies',
  'Planks',
  'Benz',
  'Lean',
  'Kill',
  'Felony',
  'Milli',
  'Grillz',
  'Evil',
  'Shooter',
  'Colt',
  '40',
  'Striker',
  'Nightwolf',
  'Dagger',
  'Abstract',
  'Name',
  'Death Note',
  'Face',
  'Stunt',
  'Flip',
  'Sick',
  'Mane',
  'Pharoah ',
  'Mask',
  'Scaryface',
  'Hurt',
  'Vicious',
  'Danger',
  'Nothing',
  'Underworld',
  'Cloak',
  'Juice',
  'Roller',
  'XXX',
  'Mixtape',
  'Hype',
  'Doublecup',
  'Perpp',
  'Purppp',
  'Phace',
  'Cyphe',
  'Night',
  'Sadness',
  'Hurt',
  'QQ',
  'Dead',
  'Killa',
  'Problem',
  'Dagger',
  'Savage',
  '$tuntz',
  'VHS',
  'Banz',
  'Bans',
  'Creep',
  'Pinch',
  'Boy',
  'Nasty',
  'Ice Cream',
  'Boom',
  'Vault',
  'Stacks',
  'Money Phone',
  'Spin',
  'Clink',
  'Keef',
  '3000',
  '9000',
  'Computer',
  'Crutches' ]
var bodyStart = [ 'The only way to Soundcloud rap fame is with a Soundcloud rapper name.']
function bodyDisplay() {
    var randBody = Math.floor(Math.random() * (bodyStart.length));
    document.getElementById('nameDisplay').innerHTML = bodyStart[randBody];
}
  //var prefixTitle = fs.readFileSync('first.txt').toString().replace(/\r\n/g,'\n').split("\n");
    /*for(i in prefixTitle) {
        console.log(prefixTitle[i]);
    }*/
//Read and store the first name into an array
//var firstName = fs.readFileSync('second.txt').toString().replace(/\r\n/g,'\n').split("\n");
   /* for(i in firstName) {
        console.log(firstName[i]);
    }*/
//Read and store last name or suffix into an array
//var lastSuffix = fs.readFileSync('third.txt').toString().replace(/\r\n/g,'\n').split("\n");
    /*for(i in lastSuffix) {
        console.log(lastSuffix[i]);
    }*/
//console.log(prefixTitle.length);
//console.log(firstName[2]);
//console.log(lastSuffix[3]);
//newNama first randomly generates which string to pull from each array, and then creates a name.
function newName() {
    var randPre = Math.floor(Math.random() * (prefixTitle.length));
    var randFirst = Math.floor(Math.random() * (firstName.length));
    var randLast = Math.floor(Math.random() * (lastSuffix.length));
    var randChance = Math.floor(Math.random() * 100);
    if (randChance < 37 || 80 < randChance) {
        randPre = randPre
        randLast = randLast
    } else if (37 <= randChance && randChance <= 47){
        randPre = 0;
    } else if (52 <= randChance && randChance <= 62){
        randLast = 0;
    } else if (62 < randChance && randChance <= 80){
            randPre = 1;
    } else {
        randPre = 0;
        randLast = 0;
    }
    document.getElementById('nameDisplay').innerHTML = prefixTitle[randPre] +' '+ firstName[randFirst] +' '+ lastSuffix[randLast];
    //return prefixTitle[randPre] +' '+ firstName[randFirst] +' '+ lastSuffix[randLast];
}
//console.log(newName());
